apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web-color
spec:
  selector:
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      containers:
        - name: web-color
          image: kubedevio/web-color:green