apiVersion: v1
kind: Service
metadata:
   name: web-service
spec:
  selector:
    app: web-color
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30000
  type: NodePort