apiVersion: v1
kind: LimitRange
metadata:
  name: limite-container
spec:
  limits:
    - min: 
        cpu: "150m"
        memory: "99Mi"
      max: 
        cpu: "800m"
        memory: "990Mi"
      default:
        cpu: "250m"
        memory: "128Mi"
      defaultRequest:
        cpu: "150m"
        memory: "100Mi"
      type: Container

